Stack nix (#1114)
* Added Nix build via haskell.nix

This makes it possible to build all the Haskell packages as Nix
expressions. Also makes cross-compiling for x86_64-linux-musl (to
produce highly portable statically linked executables) very easy.

* enable strip + disable shared for smaller binaries

* added tentative flake support

* generate flake.lock

* cleanup

* [nix] extra git deps, fix for llvm-hs build

* fix llvm-hs on musl

* use flakes exclusively + add compat shims for nix-build/nix-shell

* fixup!

* remove unused niv sources

* enable x86_64-darwin

* Updated documentation

* flake: use nixpkgs from a single source

* different nix build shell for stack

* Change the Stack generation to use the custom script

* run the generation

* Add git for stack

* remove overlays

* flake devshell

* Use numtide/devshell

* materialize nix

* refact

* fix stack.nix

* switch to haskellLib.cleanGit src filter

* add juvix-docs nix build env, add local hoogle server launcher

* update documentation

* docs: add note about trusted-users

* stack.nix: load project as git repo

* Revert "switch to haskellLib.cleanGit src filter"

This reverts commit 6f12d2f803aeee83a3eb24ca001d5c283ad840d0.

* Add nix to stdlib

* add darwin overlay template

* Adds fix for ldb on darwin-{x86_64, aarch64}

Without this fix the ldb build fails with:

ERROR: Python module pytdb of version 1.4.3 not found, and bundling
disabled

pytdb should be built as part of the tdb package (which is a dependency
of ldb), however the ldb build cannot find it.

However, the ldb source contains a copy of the tdb source and so the
pytdb module is rebuilt if the "--bundled-libraries=ALL" flag is set.
This fixes the issue

Co-authored-by: Samuli Thomasson <samuli.thomasson@pm.me>
Co-authored-by: mariari <mariari@protonmail.com>
Co-authored-by: Paul Cadman <git@paulcadman.dev>